### ISSUE TITLE
Image and album grid only display two columns in ie

### ISSUE THREAD

**Issue by BlackSkorpio** [BlackSkorpio/OxyGen#5]

**Comment by BlackSkorpio** [comment]
Removing width: calc(100% /3); from .grid li {} seams to fix the IE bug i IE11.
Strange since calc() is IE code

IE11 then using the fallback: width: 33.33%

**Comment by Hard-One** [comment]
Seems to work. Can't verify any strange behaviour in IE 11. I think you can close this issue.

**Comment by BlackSkorpio** [comment]
Sounds good

**Comment by ghost** [comment]
Hey, @BlackSkorpio, did you get this fixed? I couldn't reply in the forums. I haven't actually looked at it in the browser but it could be because you're missing a space in your code. Math operators are required to have spaces on both sides. Browsers are sometimes forgiving of syntax errors and it may be that Chrome, FFx and Safari all figured out what you wanted but IE stubbornly insists that the syntax be correct. It's been known to happen.

**Comment by BlackSkorpio** [comment]
Hi @iamdave210 
It was reported as an "non-issue" so i closed it both here and the forum thread over at the forum...

But thanks for the reminder, and the hint...

Unfortunate the spaces did nothing, but i did some more Goggling and find what i think will work (it displays as expected on my dev install at least...

Using max-width instead of just width for IE did the trick...
https://github.com/Koken-Community-Support/OxyGen/commit/aec6aeb1a093668dde77938455934f2c48df5375
